### ISSUE TITLE
"preserve_hierarchy": true broken since 2.0.13

### ISSUE THREAD

**Issue by JustArchi** [crowdin/crowdin-cli-2#34]
I'm running crowdin-cli on Windows with following base config:

Command: ```crowdin -b master --identity tools\\crowdin-cli\\crowdin_identity.yaml upload sources```

Base YAML config:

```
"preserve_hierarchy": true
files:
  - source: /ArchiSteamFarm/Localization/Strings.resx
    translation: /ArchiSteamFarm/Localization/Strings.%locale%.resx
  - source: /ConfigGenerator/Localization/CGStrings.resx
    translation: /ConfigGenerator/Localization/CGStrings.%locale%.resx
```

(identity config contains only api key and project name)

This works perfectly fine in version 2.0.12, that results in following output:

```
Creating branch 'master' - SKIPPED
File 'master/ArchiSteamFarm/Localization/Strings.resx' - SKIPPED
File 'master/ConfigGenerator/Localization/CGStrings.resx' - SKIPPED
```

Updating crowdin-cli to 2.0.13 results in following not intended output for the same command/config:

```
Creating branch 'master' - SKIPPED
File 'master/Strings.resx' - OK
File 'master/CGStrings.resx' - OK
```

This is a regression to me, structure is no longer preserved. I tried several tricks such as replacing `/` with `\\`, as well as moving my entire structure to JSON but that didn't help. I'll stick with crowdin-cli 2.0.12 until this is fixed.

Thank you in advance.
