### ISSUE TITLE
uploading: Error: String index out of range: -1

### ISSUE THREAD

**Issue by snoek09** [crowdin/crowdin-cli-2#48]
We're moving from the ruby crowdin-cli to this java crowdin-cli-2 version.
Are any configuration changes needed? Uploading is currently not working for us.
After running `java -jar crowdin-cli.jar upload sources` I get this error:
`Error: String index out of range: -1`

This is the configuration:
```
project_identifier: SOME-IDENTIFIER
api_key: SOME-API-KEY
base_url: https://api.crowdin.com
base_path: .

files:
  -
    source: '/translations/en_GB/**/*.xliff'
    translation: '/translations/%locale_with_underscore%/**/%original_file_name%'
```
